# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c74fae02f75f49d6b58994f7716d5ee"
application_url = "https://disclaimers-thing-vegetable-and.trycloudflare.com"
embedded = true
name = "ProductOption"
handle = "productoption-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_themes"

[auth]
redirect_urls = [
  "https://disclaimers-thing-vegetable-and.trycloudflare.com/auth/callback",
  "https://disclaimers-thing-vegetable-and.trycloudflare.com/auth/shopify/callback",
  "https://disclaimers-thing-vegetable-and.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
